[Unit]
# Remove the X11-only restriction
ConditionPathExists=

[Service]
# Launch ssh-agent directly, binding to the socket path used in .zshrc
ExecStart=
ExecStart=/usr/bin/ssh-agent -D -a %t/ssh-agent.socket
ExecStopPost=

[Install]
WantedBy=default.target
