require('leo.plugins')
require('leo.sets')
require('leo.autocmds')
require('leo.mappings')
require('leo.statusline')
require('leo.lsp.installer')
require('leo.lsp')
require('leo.telescope')
require('leo.cmp')
require('leo.dashboard')
require('leo.gitsigns')
require('leo.bufferline')
require('leo.toggleterm')
require('leo.indent')
require('leo.which-key')
require('leo.neogit')

vim.g.material_style = "deep ocean"
vim.cmd('colorscheme material')
